apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleeper
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
    volumeMounts:
    - mountPath: /data
      name: xx123
  volumes:
  - name: xx123
    persistentVolumeClaim:
      claimName: bbox-data
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-slacker
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "1000000"
    name: busybox
    volumeMounts:
    - mountPath: /data
      name: xx123
  volumes:
  - name: xx123
    persistentVolumeClaim:
      claimName: bbox-data

