apiVersion: v1
kind: Pod
metadata:
  name: bbox-sleeper
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /data
      name: xx123
  volumes:
  - name: xx123
    persistentVolumeClaim:
      claimName: bbox-data
---
apiVersion: v1
kind: Pod
metadata:
  name: bbox-slacker
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - mountPath: /data
      name: xx123
  volumes:
  - name: xx123
    persistentVolumeClaim:
      claimName: bbox-data
