##### Portworx/CSI storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-bbox-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  shared: "true"
---
##### Portworx/CSI persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bbox-data
spec:
  storageClassName: px-bbox-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
